name: Continuous Integration of Branch

env:
  AZURE_WEBAPP_NAME: your-app-name  # set this to the name of your Azure Web App
  PYTHON_VERSION: '3.7'              # set this to the Python version to use

on:
  # push:
  #   branches: [ "feature/*" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Edge
        run: |
          sudo apt-get update
          sudo apt update
          sudo apt install software-properties-common apt-transport-https wget
          wget -q https://packages.microsoft.com/keys/microsoft.asc -O- | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main"
          sudo apt install microsoft-edge-dev

      - name: Set up Python version
        uses: actions/setup-python@v3.0.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)
      - name: Super-Linter
        uses: github/super-linter@v4.10.1
        env:
          VALIDATE_PYTHON_PYLINT: true
          VALIDATE_PYTHON_BLACK: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run pytest
        run: python -m pytest
