name: Build and deploy Python app to Azure Web App Staging Slot

on:
  workflow_run:
    workflows: ["Build and deploy Python app to Azure Web App Staging Slot"]
    types:
      - completed
  workflow_dispatch:

env:
  APP_NAME: ${{ vars.WEBAPP_NAME }}
  LOAD_TEST_RESOURCE: ${{ vars.LOAD_TEST_RESOURCE }}
  LOAD_TEST_RESOURCE_GROUP: ${{ vars.RESOURCE_GROUP }}
  LOCATION: "eastus"

jobs:
  test:
    environment: Development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        continue-on-error: false
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} # set this through a service principal and save as a GitHub secret
          # https://github.com/marketplace/actions/azure-load-testing#azure-service-principal-for-rbac - don't run in Git Bash 

      - name: Create Azure Load Testing resource
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: ${{ env.LOAD_TEST_RESOURCE_GROUP }}
          template: ./arm_templates/template.json
          parameters: name=${{ env.LOAD_TEST_RESOURCE }} location="${{ env.LOCATION }}"

      - name: 'Azure Load Testing'
        uses: azure/load-testing@v1
        with:
          loadTestConfigFile: './load_testing/config.yaml'
          loadTestResource: ${{ env.LOAD_TEST_RESOURCE }}
          resourceGroup: ${{ env.LOAD_TEST_RESOURCE_GROUP }}
          env: |
            [
              {
              "name": "webapp",
              "value": "${{ env.APP_NAME }}-staging.azurewebsites.net"
              }
            ]

      - name: 'Upload results'
        uses: actions/upload-artifact@v2
        with:
          name: loadTestResults
          path: ${{ github.workspace }}/loadTest