name: Build and deploy Python app to Azure Web App Staging Slot

on:
  push:
    branches: [ "development" ]
  workflow_dispatch:

env:
  APP_NAME: ${{ vars.WEBAPP_NAME }} # update this for your app name
  RESOURCE_GROUP: ${{ vars.RESOURCE_GROUP }} # update this or set this to the same RG as the app
  LOCATION: "eastus"
  PYTHON_VERSION: '3.9'              # set this to the Python version to use

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python version
        uses: actions/setup-python@v3.0.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # # Optional: Add step to run tests here (PyTest, Django test suites, etc.)
      # - name: Super-Linter
      #   uses: github/super-linter@v4.10.1
      #   env:
      #     VALIDATE_PYTHON_BLACK: true
      #     VALIDATE_PYTHON_PYLINT: true
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Run pytest
      #   run: python -m pytest

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: |
            .
            !venv/

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest

    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Login to Azure
        uses: azure/login@v1
        continue-on-error: false
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} # set this through a service principal and save as a GitHub secret
          # https://github.com/marketplace/actions/azure-load-testing#azure-service-principal-for-rbac - don't run in Git Bash 

      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app
          path: .

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.APP_NAME }}
          slot-name: 'staging'
