name: Create App Service with Staging Deployment Slot

on:
  push:
    branches: [ "startup-branch" ]

env:
  APP_NAME: ${{ vars.WEBAPP_NAME }} # update this for your app name
  RESOURCE_GROUP: ${{ vars.RESOURCE_GROUP}}    # update this or set this to the same RG as the app
  LOCATION: "eastus"            # set to the same region as RG
  PYTHON_VERSION: '3.7'         # set this to the Python version to use

permissions:
  contents: read

jobs:
  createResources:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        continue-on-error: false
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} # set this through a service principal and save as a GitHub secret
          # https://github.com/marketplace/actions/azure-load-testing#azure-service-principal-for-rbac - don't run in Git Bash 

      - name: Create Azure WebApp Resource
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: ${{ env.RESOURCE_GROUP }}
          template: ./arm_templates/app_service_arm.json
          parameters: webAppName=${{ env.APP_NAME }} location="${{ env.LOCATION }}"

  validateEnvs:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Update PUBLISH_PROFILEs
        run: echo "Ensure GH Secrets are set"

  buildApplication:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python version
        uses: actions/setup-python@v3.0.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: |
            .
            !venv/

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app
          path: .

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.APP_NAME }}  
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}